version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange_rate
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      JWT_SECRET: MySecretJWT@$3213$
